// GENERATED by scripts/normalize-partner-logos.mjs — do not edit by hand.
// Run `npm run normalize:logos` after adding or changing a partner SVG.

export type PartnerLogoNormalization = { scale: number; width: number; height: number };

/** Per-brand optical scale (aspect-calibrated) + tight intrinsic dimensions. */
export const PARTNER_LOGO_NORMALIZATION: Record<string, PartnerLogoNormalization> = {
  "Adidas": { scale: 0.94, width: 717.8, height: 483.64 },
  "Amazon": { scale: 1, width: 602.35, height: 182 },
  "Apple": { scale: 0.673, width: 814, height: 1000 },
  "Bloomberg": { scale: 1, width: 300, height: 60.47 },
  "Coca-Cola": { scale: 1, width: 615.08, height: 192.94 },
  "GE": { scale: 0.719, width: 490.18, height: 490.18 },
  "Google": { scale: 1, width: 269.71, height: 89.05 },
  "L'Oreal": { scale: 1, width: 800, height: 144.75 },
  "LUMINE": { scale: 1, width: 180, height: 40 },
  "Morrison Foerster": { scale: 1, width: 264.89, height: 62.85 },
  "Netflix": { scale: 1, width: 1024, height: 276.74 },
  "Nike": { scale: 1, width: 999.67, height: 356.39 },
  "Spotify": { scale: 1, width: 558.35, height: 168 },
  "Toyota": { scale: 0.826, width: 60, height: 39 },
};
